workflows:
  ios-workflow:
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/**/*.ipa
